#!/bin/bash
while true; do
r=$(zenity --question --title="alarms" --text="alarms menu" --switch --extra-button="alarms" --extra-button="new alarm" --extra-button="remove alarms" --extra-button="back")
if [ "$r" == "alarms" ]; then
        ./list_alarms

elif [ "$r" == "new alarm" ]; then
	./new_alarm
elif [ "$r" == "remove alarms" ]; then
	./remove_alarm
elif [ $r == "back" ]; then
	break
fi
done
