#!/bin/bash
cd ..
t=$(zenity --forms --title="alarm" --text="set alarm" --add-entry="time:")
echo $PWD/alert/alarm_alert "$t" | at $t -q "t"
echo $PWD/alert/alarm_alert $t
if [ $? == 0 ]; then
zenity --info --text="alarm set for $t"
else
zenity --error --title="alarm" --text="failed to set alarm!"
fi
