#!/bin/bash
t=$(zenity --forms --title="set timer" --text="set timer" --add-entry="time:")
sleep $t | zenity --progress --text="timer running" --pulsate --auto-close --auto-kill
cd ..
zenity --info --text="timer done" | mplayer $(cat alert/alert)
